# Generated by Django 2.2.2 on 2019-06-17 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Loan_client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('birth_date', models.DateField()),
                ('work_experience', models.IntegerField(default=0)),
                ('gross_salary', models.IntegerField(default=0)),
                ('dependents', models.IntegerField(default=0)),
                ('current_loan_total', models.IntegerField(default=0)),
                ('loan_history', models.CharField(default='ok', max_length=6)),
                ('rating', models.IntegerField(default=0)),
            ],
        ),
    ]
