# Generated by Django 2.2.2 on 2019-06-17 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan_client',
            name='loan_history',
            field=models.CharField(choices=[('ok', 'OK'), ('not ok', 'NOT OK')], default='ok', max_length=6),
        ),
    ]
