# Generated by Django 2.2.2 on 2019-06-17 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190617_1444'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan_client',
            old_name='current_loan_total',
            new_name='current_monthly_payments',
        ),
        migrations.RemoveField(
            model_name='loan_client',
            name='rating',
        ),
        migrations.AddField(
            model_name='loan_client',
            name='education',
            field=models.CharField(choices=[('elementary school', 'ELEMENTARY SCHOOL'), ('high school', 'HIGH SCHOOL'), ('bs/ba', 'BS/BA'), ('master', 'MASTER'), ('phd', 'PHD')], default='bs/ba', max_length=6),
        ),
        migrations.AddField(
            model_name='loan_client',
            name='tax_rate',
            field=models.CharField(choices=[('0.35', '0.35'), ('0.45', '0.45')], default='0.45', max_length=4),
        ),
        migrations.AlterField(
            model_name='loan_client',
            name='loan_history',
            field=models.CharField(choices=[('ok', 'OK'), ('not ok', 'NOT OK')], default='ok', max_length=18),
        ),
    ]
