# Generated by Django 2.2.2 on 2019-06-17 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190617_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan_client',
            name='education',
            field=models.CharField(choices=[('elementary school', 'ELEMENTARY SCHOOL'), ('high school', 'HIGH SCHOOL'), ('bs/ba', 'BS/BA'), ('master', 'MASTER'), ('phd', 'PHD')], default='bs/ba', max_length=18),
        ),
        migrations.AlterField(
            model_name='loan_client',
            name='loan_history',
            field=models.CharField(choices=[('ok', 'OK'), ('not ok', 'NOT OK')], default='ok', max_length=6),
        ),
    ]
