# Generated by Django 2.2.2 on 2019-06-17 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20190617_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan_client',
            name='education',
            field=models.CharField(choices=[('elementary school', 'ELEMENTARY SCHOOL'), ('high school', 'HIGH SCHOOL'), ('bs/ba', 'BS/BA'), ('master', 'MASTER'), ('phd', 'PHD')], max_length=18),
        ),
        migrations.AlterField(
            model_name='loan_client',
            name='loan_history',
            field=models.CharField(choices=[('ok', 'OK'), ('not ok', 'NOT OK')], max_length=6),
        ),
        migrations.AlterField(
            model_name='loan_client',
            name='tax_rate',
            field=models.CharField(choices=[('0.35', '0.35'), ('0.45', '0.45')], max_length=4),
        ),
    ]
