# Generated by Django 2.2.2 on 2019-06-17 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20190617_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan_client',
            name='needed_loan',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='loan_client',
            name='return_period',
            field=models.IntegerField(default=0),
        ),
    ]
