# Generated by Django 2.2.2 on 2019-06-17 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20190617_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan_client',
            name='current_monthly_payments',
            field=models.IntegerField(default=0, help_text='total loan payments in RON'),
        ),
        migrations.AlterField(
            model_name='loan_client',
            name='dependents',
            field=models.IntegerField(default=0, help_text='the number of children + unemployed family members'),
        ),
        migrations.AlterField(
            model_name='loan_client',
            name='gross_salary',
            field=models.IntegerField(default=0, help_text='use RON values'),
        ),
        migrations.AlterField(
            model_name='loan_client',
            name='needed_loan',
            field=models.IntegerField(default=0, help_text='the amount requested by the client, in RON'),
        ),
        migrations.AlterField(
            model_name='loan_client',
            name='return_period',
            field=models.IntegerField(default=0, help_text='the number of years to return the loan'),
        ),
        migrations.AlterField(
            model_name='loan_client',
            name='tax_percent',
            field=models.IntegerField(default=45, help_text='the percentage of all salary taxes'),
        ),
        migrations.AlterField(
            model_name='loan_client',
            name='work_experience',
            field=models.IntegerField(default=0, help_text='experience in years'),
        ),
    ]
