# Generated by Django 2.2.2 on 2019-06-19 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20190619_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan_client',
            name='cname',
            field=models.CharField(default='Ralalala', max_length=41),
            preserve_default=False,
        ),
    ]
