# Generated by Django 2.2.2 on 2019-06-19 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_remove_loan_client_cname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan_client',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='loan_client',
            name='last_name',
        ),
        migrations.AddField(
            model_name='loan_client',
            name='cname',
            field=models.CharField(default='xxx', help_text='Last name, first name', max_length=20),
            preserve_default=False,
        ),
    ]
