# Generated by Django 2.2.2 on 2019-06-23 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_loan_client_receiving_income'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan_client',
            old_name='gross_salary',
            new_name='gross_income',
        ),
        migrations.AlterField(
            model_name='loan_client',
            name='tax_percent',
            field=models.IntegerField(default=45, help_text='the percentage of all income taxes'),
        ),
    ]
