# Generated by Django 2.2.2 on 2019-06-23 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20190623_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan_client',
            name='sex',
            field=models.CharField(choices=[('m', 'M'), ('f', 'F'), ('o', 'O')], default='m', max_length=1),
            preserve_default=False,
        ),
    ]
