# Generated by Django 2.2.2 on 2019-06-23 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_loan_client_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan_client',
            name='sex',
            field=models.CharField(choices=[('M', 'M'), ('F', 'F'), ('O', 'O')], max_length=1),
        ),
    ]
