# Generated by Django 2.2.2 on 2019-06-23 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20190623_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan_client',
            name='sex',
            field=models.CharField(choices=[('m', 'M'), ('f', 'F'), ('o', 'O')], max_length=1),
        ),
    ]
