# Generated by Django 2.2.2 on 2019-06-27 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20190623_1749'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nutrition_client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('sex', models.CharField(choices=[('m', 'M'), ('f', 'F'), ('o', 'O')], max_length=1)),
                ('initial_weight', models.IntegerField(default=0, help_text='kg values')),
                ('workout', models.CharField(choices=[('once/week', 'ONCE/WEEK'), ('twice/week', 'TWICE/WEEK'), ('more', 'MORE')], max_length=10)),
                ('avg_stress_level', models.CharField(choices=[('low', 'LOW'), ('medium', 'MEDIUM'), ('high', 'HIGH')], max_length=6)),
                ('diet', models.CharField(choices=[('low fat', 'LOW FAT'), ('low carbs', 'LOW CARBS'), ('both', 'BOTH')], max_length=9)),
                ('weight_1_month', models.IntegerField(default=0, help_text='kg values')),
                ('weight_3_months', models.IntegerField(default=0, help_text='kg values')),
            ],
        ),
    ]
