# Generated by Django 2.2.2 on 2019-06-27 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_nutrition_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutrition_client',
            name='age',
            field=models.IntegerField(default=0, help_text='years'),
        ),
    ]
